# apiVersion: scheduling.k8s.io/v1
# kind: PriorityClass
# metadata:
#   name: low-priority-class
# value: 10
# globalDefault: false
# description: "This priority class should be used for low priority fah-cpu pods only."

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fah-cpu
  labels:
    app: fah-cpu
spec:
  selector:
    matchLabels:
      app: fah-cpu
  replicas: 2 # Set number of replicas to run - one replica per node
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
      maxSurge: 100%
  template:
    metadata:
      labels:
        app: fah-cpu
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - fah-cpu
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: fah-cpu
          image: "ghcr.io/richstokes/k8s-fah:master"
          # --run-as UID should match runAsUser value in containers securityContext
          command:
            - "/usr/bin/FAHClient"
            - "--config"
            - "/var/lib/fahclient/config.xml"
            - "--config-rotate=false"
            - "--run-as"
            - "1234"
            - "--pid-file=/var/lib/fahclient/fahclient.pid"
            - "--gpu=false"
          resources:
            limits:
              cpu: 1000m # How much CPU you wish to donate per node
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 512Mi
          # Make the container harder to break out of or exploit
          securityContext:
            runAsNonRoot: true
            # UID needs to be defined to not default to root on kubernetes.
            # If you are using OpenShift, patch to remove runAsUser
            # oc patch deployment fah-cpu -p '{"spec":{"template":{"spec":{"containers":[{"name":"fah-cpu","securityContext":{"runAsUser":null}}]}}}}'
            # oc patch deployment fah-cpu -p '{"spec":{"template":{"spec":{"initContainers":[{"name":"copy-config","securityContext":{"runAsUser":null}}]}}}}'
            runAsUser: 1234
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          volumeMounts:
            - mountPath: /var/lib/fahclient
              name: fahclient
      # We make an emptyDir to mount on the work directory /var/lib/fahclient
      # so we can make the rest of the container's root filesystem read-only
      volumes:
        - name: fahclient
          emptyDir: {}
        # Uncomment if using ConfigMap config.xml
        # - name: fah-cpu-config
        #   configMap:
        #     name: foldingathome-config
      initContainers:
        - name: copy-config
          imagePullPolicy: Always
          image: "ghcr.io/richstokes/k8s-fah:master"
          command:
            - "sh"
            - "-c"
            - "cp /etc/fahclient/config.xml /var/lib/fahclient/config.xml"
            # Use following lines if using ConfigMap config.xml
            # - "cp"
            # - "/etc/fahclient-config/config.xml"
            # - "/var/lib/fahclient/config.xml"
          securityContext:
            runAsNonRoot: true
            # UID needs to be defined to not default to root on kubernetes.
            # If you are using OpenShift, patch to remove runAsUser
            # oc patch deployment fah-cpu -p '{"spec":{"template":{"spec":{"containers":[{"name":"fah-cpu","securityContext":{"runAsUser":null}}]}}}}'
            # oc patch deployment fah-cpu -p '{"spec":{"template":{"spec":{"initContainers":[{"name":"copy-config","securityContext":{"runAsUser":null}}]}}}}'
            runAsUser: 1234
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          volumeMounts:
            - mountPath: /var/lib/fahclient
              name: fahclient
            # Uncomment if using ConfigMap config.xml
            # - name: fah-cpu-config
            #   mountPath: /etc/fahclient-config
      # priorityClassName: low-priority-class
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: foldingathome-config
data:
  config.xml: |
    <config>
      <!--
        To set your user name, team and passkey just edit the text
        in quotes below.
      -->

      <!-- User Information -->
      <user value=""/> <!-- Enter your user name here -->
      <team value=""/>         <!-- Your team number -->
      <passkey value=""/>       <!-- 32 hexadecimal characters if provided -->

      <power value="full"/>     <!-- Throttling this at K8s level -->
      <gpu value="false"/>      <!-- If true, attempt to autoconfigure GPUs -->
      <fold-anon value="false"/>

      <!-- Folding Slots
        No folding slot configuration is necessary.  The client will
        automaticlaly choose a good configuration for you.  However, here
        are some examples:
      
          <slot id="0" type="CPU"/>

        or
        
          <slot id="0" type="CPU"/>
          <slot id="1" type="GPU"/>

        All slots in a configuration MUST have unique ids.
      -->
    </config>
---
