kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fah-gpu-claim
  namespace: nrevo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  storageClassName: ocs-storagecluster-cephfs

